import Note from "./Note";
/*
 * @Author: Joshua Eigbe self@joshuaeigbe.com
 * @Github: https://github.com/jsh007
 * @Date: 2024-01-11 14:40:29
 * @LastEditors: Joshua Eigbe jeigbe@gmail.com
 * @LastEditTime: 2024-01-28 15:08:58
 * @FilePath: /quicktickets_frontend/src/features/notes/NotesList.jsx
 * @copyrightText: Copyright (c) Joshua Eigbe. All Rights Reserved.
 * @Description: See Github repo
 */
import { PulseLoader } from "react-spinners";
// import { selectUsersById } from "../users/usersApiSlice";
import useAuth from "../../hooks/useAuth";
import { useGetNotesQuery } from "./notesApiSlice";
// import { useSelector } from "react-redux";

const NotesList = () => {
  const { username, isAdmin, isManager } = useAuth();
  // const currentUser = useSelector(selectUsersById(state, no))

  const {
    data: notes,
    isSuccess,
    isLoading,
    isError,
    error,
  } = useGetNotesQuery("notesList", {
    pollingInterval: 15000,
    refetchOnFocus: true,
    refetchOnMountOrArgChange: true,
  });

  let content;
  if (isLoading) content = <PulseLoader color={"#FFF"} />;
  if (isError)
    content = <p className="errmsg">`Error - {error?.data?.message}`</p>;
  // if (isError) content = <PulseLoader color={"#FFF"} />;

  if (isSuccess) {
    const { ids, entities } = notes;
    // console.log(notes);

    let filteredIds;
    // if (isAdmin || isManager) {
    //   filteredIds = [...ids];
    // } else {
    //   // Find a way to create notes that has a username field in addition to existing user field.;
    //   filteredIds = ids.filter(
    //     // username  is not relable because it can be changed by user. either set a autogenerated id  or use the document id.
    //     // Alternatively, fetch a User document from the DB and spread the username field to the note object before sending the response.
    //     // Always seek to solve fetch issues in the Backend before trying to do it in the Frontend
    //     (noteId) => entities[noteId].username === username // This should work because username was spread to the note object before sending the response from getNotes()
    //   );
    // }

    if (isManager || isAdmin) {
      filteredIds = [...ids];
    } else {
      filteredIds = ids.filter(
        (noteId) => entities[noteId].username === username
      );
    }

    const tableContent =
      ids?.length &&
      filteredIds.map((noteId) => <Note key={noteId} noteId={noteId} />); // Returns a row of notes data to the table

    content = (
      <table className="table table--notes">
        <thead className="table__thead">
          <tr>
            <th scope="col" className="table__th note__status">
              Status
            </th>
            <th scope="col" className="table__th note_title">
              Title
            </th>
            <th scope="col" className="table__th note_username">
              Owner
            </th>
            <th scope="col" className="table__th note_edit">
              Edit
            </th>
          </tr>
        </thead>
        <tbody>{tableContent}</tbody>
      </table>
    );
  }
  return content;
};

export default NotesList;
